# Generated by Django 3.0.4 on 2020-04-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200430_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
