# Generated by Django 3.0.4 on 2020-04-27 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='main_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment'),
        ),
    ]
