# Generated by Django 3.0.4 on 2020-03-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
