# Generated by Django 3.0.4 on 2020-03-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_coursecategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
