# Generated by Django 3.0.4 on 2020-03-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20200326_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
