# Generated by Django 3.0.4 on 2020-03-26 09:23

import content.fields
import courses.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=20, null=True)),
                ('course_discription', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to=courses.utils.file_path)),
                ('views', models.IntegerField(default=0)),
                ('video_count', models.IntegerField(default=0)),
                ('excersise_count', models.IntegerField(default=0)),
                ('level', models.CharField(choices=[('clueless', 'Clueless'), ('newbie', 'Newbie'), ('got an idea', 'Got an idea'), ('expert', 'Expert')], max_length=100)),
                ('number_of_chapters', models.IntegerField(default=0)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('membership_required', models.BooleanField(default=False)),
                ('free', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.CourseCategory')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ManyToManyField(blank=True, related_name='owned', to='courses.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MyCourse',
                'verbose_name_plural': 'MyCourses',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('chapter_name', models.CharField(max_length=250)),
                ('chapter_number', models.IntegerField(default=0)),
                ('chapter_description', models.TextField()),
                ('order', content.fields.PositionField(default=-1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('course', 'chapter_name'), name='unique_chapter'),
        ),
    ]
