# Generated by Django 3.0.4 on 2020-03-26 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('courses', '0003_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='other_category',
            field=models.ManyToManyField(null=True, related_name='secondary_category', to='category.CourseCategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_category', to='category.CourseCategory'),
        ),
    ]
