# Generated by Django 3.0.4 on 2020-03-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('courses', '0004_auto_20200326_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='other_category',
            field=models.ManyToManyField(blank=True, related_name='secondary_category', to='category.CourseCategory'),
        ),
    ]
