# Generated by Django 3.0.4 on 2020-04-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200326_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='preivew',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
    ]
