# Generated by Django 3.0.4 on 2020-05-07 09:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0002_auto_20200507_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership_end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 9, 56, 58, 814197, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='membership_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 9, 56, 58, 814149, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
