# Generated by Django 3.0.4 on 2020-04-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_chapter_preivew'),
        ('content', '0003_auto_20200402_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='embeded_content',
        ),
        migrations.AddField(
            model_name='contents',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course'),
        ),
    ]
