# Generated by Django 3.0.4 on 2020-04-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_contents_share_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='share_message',
            field=models.CharField(default='Learn more with Rise Elearning at', max_length=150),
        ),
    ]
